add support for hidePostCTA setting
Kommunicate-io/Kommunicate-Android-Chat-SDK pull request #202
Opened 2021-05-19 14:32 UTC by reytum

* If the setting is enabled, only the latest rich message will be visible.
* If there is a sent message after the last rich message, then no rich messages will be visible.

2021-05-19 15:26 UTC, devashishmamgain requested changes

2021-05-19 15:26 UTC, devashishmamgain commented
@reytum can you share apk also

2021-05-19 15:29 UTC, reytum commented on kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
> +        int index = messageList.indexOf(message);
Sorry forgot to remove it.

2021-05-19 15:29 UTC, reytum commented on kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/Message.java
> +        return metadata != null && "300".equals(metadata.get("contentType"));
Ok

2021-05-19 15:48 UTC, devashishmamgain approved these changes

2021-05-20 04:25 UTC, devashishmamgain requested changes
generic card, list template, images, etc is not working

2021-05-20 09:14 UTC, reytum commented
> generic card, list template, images, etc is not working

Did the changes. Now all the rich messages after the last sent message will be visible.

2021-06-04 06:48 UTC, devashishmamgain approved these changes

2021-06-15 12:46 UTC, merged