[CM-939] - Added support to set default conversation settings
Kommunicate-io/Kommunicate-Android-Chat-SDK pull request #275
Opened 2022-05-30 11:16 UTC by amntoppo

## What do you want to achieve?
- To create a default conversation setting, which can be used with "Start new conversation" button on the conversation list page.
- Added these methods:
```java
KmSettings.setDefaultBotIds(List<String> botIds) 
KmSettings.setDefaultAgentIds(List<String> agentIds)
KmSettings.setDefaultAssignee(String assigneeId)
KmSettings.setDefaultTeamId(String teamId)
KmSettings.clearDefaultSettings()
```
- Saves the settings to KmDefaultSettingPreference. To clear the default data, `KmSettings.clearDefaultSettings()` can be used.
- Also, modified existing preference for better code structure.

2022-05-30 16:13 UTC, Sathyan-Elangovan requested changes

2022-05-30 16:13 UTC, Sathyan-Elangovan commented on kommunicate/src/main/java/io/kommunicate/KmConversationHelper.java
> +            if(KmDefaultSettingPreference.getInstance().getDefaultAssignee() != null) {
create a single instance for `KMDefaultSettingPreference.getInstance()` & use it for all.

2022-05-31 06:42 UTC, Sathyan-Elangovan approved these changes

2022-06-01 13:13 UTC, adarshmishra approved these changes

2022-06-02 11:54 UTC, merged