[CM-1007] Changed notification icon color
Kommunicate-io/Kommunicate-Android-Chat-SDK pull request #287
Opened 2022-07-20 05:25 UTC by pahadi777

Changed notification icon color

2022-07-20 05:37 UTC, amntoppo requested changes

2022-07-20 05:37 UTC, amntoppo commented on kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
> +    private final String DEFAULT_NOTIFICATION_ICON_COLOR = "3F51B5";
Don't give a default value. 
If Metadata is not present then don't set the color.

2022-07-20 05:37 UTC, amntoppo commented on kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
> +                .setSmallIcon(notificationInfo.smallIconResourceId)
remove extra line

2022-07-20 07:13 UTC, amntoppo approved these changes

2022-07-20 07:13 UTC, amntoppo commented on kommunicate/src/main/java/com/applozic/mobicomkit/api/notification/NotificationService.java
> +import android.util.Log;
remove unused imports.

2022-07-21 06:24 UTC, Sathyan-Elangovan approved these changes
Add Changelog entry

2022-07-21 06:52 UTC, Sathyan-Elangovan requested changes
in Title add [UnReleased] instead mentioning the version. Because we have not released this version right

2022-07-21 07:11 UTC, Sathyan-Elangovan approved these changes

2022-07-21 07:24 UTC, merged