[CM-1038] Crash Fix while calling getName() at KmDocumentView.java:352
Kommunicate-io/Kommunicate-Android-Chat-SDK pull request #291
Opened 2022-08-02 13:47 UTC by pahadi777

2022-08-03 05:56 UTC, amntoppo requested changes

2022-08-03 05:56 UTC, amntoppo commented on kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/attachmentview/KmDocumentView.java
> +        if(message.getFileMetas() != null) {
FileMeta can be non-null but getName() can still be null, it will throw an exception again

2022-08-03 10:55 UTC, Sathyan-Elangovan approved these changes

2022-08-04 05:52 UTC, amntoppo approved these changes

2022-08-05 06:35 UTC, merged