CM-1392
Kommunicate-io/Kommunicate-Android-Chat-SDK pull request #377
Opened 2023-04-11 12:31 UTC by pranaysaini04

## Summary:
- Ask rating everytime when conversation is opened again.

## How was the code tested?
- Tested it on the  local device

2023-04-11 13:13 UTC, Sathyan-KM requested changes

2023-04-11 13:13 UTC, Sathyan-KM commented on kommunicate/src/main/java/com/applozic/mobicomkit/api/conversation/database/MessageDatabaseService.java
> +                cursor.moveToFirst();
@amntoppo that raw parameter query handled properly here ? please check

2023-04-11 13:13 UTC, Sathyan-KM commented on kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
>                                  //If Conversation was resolved and feedback was submitted given
Fix this comment `If Conversation was resolved and feedback was submitted given`.

2023-04-11 13:13 UTC, Sathyan-KM commented on kommunicateui/src/main/java/com/applozic/mobicomkit/uiwidgets/conversation/fragment/MobiComConversationFragment.java
> +//                                   kmFeedbackView.showFeedback(context, response.getData());
remove this if not needed

2023-04-12 07:33 UTC, amntoppoKM requested changes

2023-04-12 07:53 UTC, amntoppoKM approved these changes

2023-04-19 12:47 UTC, amntoppoKM approved these changes

2023-04-19 14:18 UTC, Sathyan-KM approved these changes

2023-04-19 14:22 UTC, merged